FROM node:20 as build

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

FROM nginx:latest

# COPY frontend/dist /usr/share/nginx/html
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 443